#!/usr/bin/env sh

if [[ ${BLOCK_BUTTON} -eq 4 ]]; then
	xbacklight -inc 5 -time 0
elif [[ ${BLOCK_BUTTON} -eq 5 ]]; then
	xbacklight -dec 5 -time 0
elif [[ ${BLOCK_BUTTON} -eq 1 ]]; then
	xset dpms force off
fi

printf '%.*f\n' 0 $(xbacklight)
