#!/usr/bin/env sh

if [[ ! `playerctl -l` ]]; then
	exit
else
	ARTIST=`playerctl metadata artist`
	TITLE=`playerctl metadata title`

	if [[ ! $ARTIST ]] || [[ ! $TITLE ]]; then
		exit
	fi

	echo "`playerctl metadata artist` - `playerctl metadata title`"
fi

case ${BLOCK_BUTTON} in
	1)
		playerctl play-pause
		;;
	4)
		playerctl next
		;;
	5)
		playerctl previous
		;;
esac

exit
