#!/usr/bin/env sh
# TODO: When closing Spotify, some null garbage is shown

if [[ ! `playerctl -l` ]]; then
	exit
else
	ARTIST=`playerctl metadata artist`
	TITLE=`playerctl metadata title`

	echo "`playerctl metadata artist` - `playerctl metadata title`"
fi

case ${BLOCK_BUTTON} in
	1)
		playerctl play-pause
		;;
	4)
		playerctl next
		;;
	5)
		playerctl previous
		;;
esac

exit
