#!/usr/bin/env sh

TEMPERATURE=`sensors | \
grep -i 'physical' | \
awk '{print $4}' | \
tr -d '+'`
LEVEL=`sensors | \
grep -i 'physical' | \
awk '{print $4}' | \
tr -d '+°C'`

echo $TEMPERATURE
echo $TEMPERATURE
if [[ $LEVEL -ge 70 ]] && [[ $LEVEL -lt 80 ]]; then
	echo \#ffa724
fi
if [[ $LEVEL -ge 80 ]]; then
	echo \#ff2c4b
fi

exit
