#!/usr/bin/env sh

case ${BLOCK_BUTTON} in
	1)
		amixer sset Master toggle >/dev/null 2>&1
		;;
	3)
		pavucontrol
		;;
	4)
		amixer sset Master 5%+ >/dev/null 2>&1
		;;
	5)
		amixer sset Master 5%- >/dev/null 2>&1
		;;
esac

VOLUME=`amixer get Master | \
grep % | \
head -1 | \
awk '{if (toupper($6) == "[ON]") {print $5} else {print "OFF"}}' | \
tr -d '[]%'`

echo $VOLUME
echo $VOLUME

exit
