#!/usr/bin/env sh
# TODO: Fix blinking when changing volume using mouse

VOLUME=`amixer get Master | \
grep % | \
head -1 | \
awk '{if (toupper($6) == "[ON]") {print $5} else {print "OFF"}}' | \
tr -d '[]%'`

echo $VOLUME
echo $VOLUME

case ${BLOCK_BUTTON} in
	1)
		amixer sset Master toggle
		;;
	3)
		pavucontrol
		;;
	4)
		amixer sset Master 5%+
		;;
	5)
		amixer sset Master 5%-
		;;
esac

exit
