#!/usr/bin/env sh

# full text, short text, color
if [[ `cat /sys/class/net/wlo1/operstate` = 'down' ]]; then
	echo 'down'
	echo 'down'
	echo \#ff2c4b
else
	SSID=`iw dev wlo1 link | \
	grep SSID | \
	cut -d ' ' -f 2-`
	ADDR=`ip addr show wlo1 | \
	grep -i 'inet\ ' | \
	awk '{print $2}'`

	echo "$SSID ($ADDR)"
	echo "$SSID ($ADDR)"
fi

exit
