#!/bin/sh

pulseaudio --start
xset -b
setxkbmap cz
nitrogen --restore
compton -b

cd .dotfiles/X
xrdb Xresources
cd $HOME

numlockx

systemctl --user import-environment DISPLAY XAUTHORITY

if which dbus-update-activation-environment >/dev/null 2>&1; then
	dbus-update-activation-environment DISPLAY XAUTHORITY
fi

HOURS=$(date +%k)
if [[ $HOURS -lt 8 || $HOURS -gt 22 ]]; then
	xbacklight -set 0
else
	xbacklight -set 15
fi

exec i3
