#!/bin/sh

pulseaudio --start
xset -b
setxkbmap cz
nitrogen --restore
compton -b

cd .dotfiles/X
xrdb Xresources
cd $HOME

numlockx

HOURS=$(date +%k)
if [[ $HOURS -lt 8 || $HOURS -gt 22 ]]; then
	xbacklight -set 0
else
	xbacklight -set 15
fi

exec i3
