#!/bin/sh

pulseaudio --start
xset -b
setxkbmap cz
nitrogen --restore
compton -b
xrdb ~/.Xresources
numlockx

HOURS=$(date +%k)
if [[ $HOURS -lt 8 || $HOURS -gt 22 ]]; then
	xbacklight -set 0
else
	xbacklight -set 25
fi

exec i3
