#!/bin/sh

# Make sure everything that is needed is available
command -v convert > /dev/null 2>&1 || { echo >&2 "imagemagick is not installed, aborting"; exit 1; }
command -v maim > /dev/null 2>&1 || { echo >&2 "maim is not installed, aborting"; exit 1; }
command -v i3lock > /dev/null 2>&1 || { echo >&2 "i3lock is not installed, aborting"; exit 1; }

IMAGE=$(mktemp --suffix .png)
maim --format png $IMAGE

WIDTH=$(convert -print "%w\n" $IMAGE /dev/null)
CENTER_X=$(expr $WIDTH / 2)
HEIGHT=$(convert -print "%h\n" $IMAGE /dev/null)
CENTER_Y=$(expr $HEIGHT / 2)
RADIUS=$(expr $CENTER_Y + 95)

BG_COLOR="363330ff"
BG_OPACITY="75%"
FG_COLOR="00ff99ff"
WRONG_COLOR="d17b49ff"

TEXT_COLOR="ffffff"
STROKE_COLOR="000000"

MONITOR_COUNT=`xrandr -q | grep ' connected' | wc -l`
if [ $MONITOR_COUNT -eq 1 ]; then
	ANNOTATE_POS="+0+160"
else
	ANNOTATE_POS="-650+160" # my 2 monitors setup
fi
# yea it's pretty ugly but it satisfies me for now

convert $IMAGE \
	-level 0%,100%,0.7 \
	-filter Gaussian \
	-resize 25% \
	-define filter:sigma=2 \
	-resize 400% \
	-font Roboto \
	-pointsize 50 \
	-fill \#$TEXT_COLOR \
	-stroke \#$STROKE_COLOR \
	-strokewidth 3 \
	-gravity center \
	-draw "text $ANNOTATE_POS 'Type password to unlock'" \
	-stroke none \
	-draw "text $ANNOTATE_POS 'Type password to unlock'" \
	$IMAGE
# Text is drawn 2 times because of stroking
# Convert strokes the text both from inner and outer side so you stroke it,
# draw once again and what you got is only outer stroke :)

# Try to run i3lock-color
i3lock \
	--insidevercolor=00000000 --insidewrongcolor=00000000 --insidecolor=00000000 \
	--ringvercolor=$FG_COLOR --ringwrongcolor=$WRONG_COLOR --ringcolor=464340ff \
	--linecolor=00000000 --textcolor=00000000 \
	--keyhlcolor=$FG_COLOR --bshlcolor=$WRONG_COLOR \
	-i $IMAGE > /dev/null

rm $IMAGE
