# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom
ZSH_THEME="kelerg"

# Case sensitive completion
CASE_SENSITIVE="true"

export UPDATE_ZSH_DAYS=14

# Display three red dots while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Date format for history stamps
HIST_STAMPS="dd/mm/yyyy"

plugins=(vi-mode git python gitignore django pip virtualenv suse)

# User configuration
export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11"
export TERM=xterm-256color
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# ssh
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

# Set account editor
export EDITOR=/usr/bin/nvim

alias ls='ls -A --color=always'

# Use nvbm/thefuck
alias fuck='eval $(thefuck $(fc -ln -1))'
alias FUCK='fuck'
